### ISSUE TITLE
文案问题#2

### ISSUE THREAD

**Issue by li-xiwu** [Pitrick3141/DontFDHere#2]
![Snipaste_2022-08-01_14-04-31](https://user-images.githubusercontent.com/63759704/182082618-27d8c2fe-b085-4a68-9903-e1bcca87fbe3.jpg)
如题

**Comment by Pitrick3141** [comment]
## 感谢你提供的文案问题！
相关问题已在最新的提交**Daily Update @ Aug 1, 2022**中修复，同时该提交也提供了**13个新的内置模板**

### 目前(v1.2.0)更新内置模板的方法：
---
**①**从GitHub Repo下载单独的模板文件或克隆整个仓库，并复制内置模板文件到**程序运行目录\FDTemplates**
**②**等待v1.3.0的Release并覆盖安装
**③**使用内置模板同步功能(目前处于实验阶段)

### 若要使用内置模板同步功能更新内置模板，请遵循以下步骤：
---
1. 在**程序运行目录\FDTemplates**下新建配置文件**allow_command.json**（文件名称可自定义，类型为json）
2. 在配置文件中写入如下序列化字符串: **{"config":true, "version":"*",  "allow_command":true}**
3. 打开程序并在输出区域输入"**SyncTemplates**"，在自定义关键词输入框输入"**Check**"
4. 等待模板同步并在弹出的窗口确认下载模板
